### ISSUE TITLE
this code have inplace bug

### ISSUE THREAD

**Issue by Lvhhhh** [ustclby/Unsupervised-Domain-Specific-Deblurring#12]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [80, 3, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
python-BaseException

**Comment by Wolfybox** [comment]
I kinda suspect that the author deliberately presented the wrong codes to prevent others' re-implementation of training.

**Comment by JayKarhade** [comment]
Hey @Lvhhhh did you find a fix to this problem? I'm facing a similar issue

**Comment by saber131421** [comment]
@Lvhhhh  please put  the self.enc_c_opt.step() , self.enc_a_opt.step()  and self.gen_opt.step() in function update_EG(self) after  self.backward_G_alone()

**Comment by YuanQiQuan** [comment]
Traceback (most recent call last):
  File "E:\Python\Unsupervised-Domain-Specific-Deblurring-master\src\train.py", line 86, in <module>
    main()
  File "E:\Python\Unsupervised-Domain-Specific-Deblurring-master\src\train.py", line 60, in main
    model.update_EG()
  File "E:\Python\Unsupervised-Domain-Specific-Deblurring-master\src\model.py", line 226, in update_EG
    self.backward_G_alone()
  File "E:\Python\Unsupervised-Domain-Specific-Deblurring-master\src\model.py", line 303, in backward_G_alone
    loss_G2.backward()
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 8]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by YuanQiQuan** [comment]
@saber131421  
```
 def update_EG(self):
    # update G, Ec, Ea
    self.enc_c_opt.zero_grad()
    self.enc_a_opt.zero_grad()
    self.gen_opt.zero_grad()
    self.backward_EG()
    self.enc_c_opt.step()
    self.enc_a_opt.step()
    self.gen_opt.step()

    # update G, Ec
    self.enc_c_opt.zero_grad()
    self.gen_opt.zero_grad()
    self.backward_G_alone()
    self.enc_c_opt.step()
    self.enc_a_opt.step()
    self.gen_opt.step()
```
As you said, I made the following changes, but it still doesn't work

**Comment by Devil-Ideal** [comment]
> @Lvhhhh please put the self.enc_c_opt.step() , self.enc_a_opt.step() and self.gen_opt.step() in function update_EG(self) after self.backward_G_alone()

thank you very much！it's working

**Comment by rose-jinyang** [comment]
Hi @HelloWorldYYYYY and @saber131421 
Did u fix this issue?
Although I followed the above suggestion, there is still the issue.

**Comment by rose-jinyang** [comment]
Hi @Devil-Ideal 
Could u share your updated code?

**Comment by zhoubin-zb** [comment]
> self.gen_opt.step()

like this:
    def update_EG(self):
        # update G, Ec, Ea
        self.enc_c_opt.zero_grad()
        self.enc_a_opt.zero_grad()
        self.gen_opt.zero_grad()
        self.backward_EG()
        # self.enc_c_opt.step()
        # self.enc_a_opt.step()
        # self.gen_opt.step()

        # update G, Ec
        self.enc_c_opt.zero_grad()
        self.gen_opt.zero_grad()
        self.backward_G_alone()
        self.enc_a_opt.step()
        self.enc_c_opt.step()
        self.gen_opt.step()
