### ISSUE TITLE
RuntimeError: reduce failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by strawberry1996** [ustclby/Unsupervised-Domain-Specific-Deblurring#4]
Hi,
Thanks for your code. But I met some problem when I run this code

/pytorch/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [30,0,0] Assertion `input >= 0. && input <= 1.` failed.
/pytorch/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [0,0,0], thread: [31,0,0] Assertion `input >= 0. && input <= 1.` failed.
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    main()
  File "train.py", line 58, in main
    model.update_D(images_a, images_b)
  File "/home/dengzeyu/run_on_server/Unsupervised-Domain-Specific-Deblurring-master/src/model.py", line 191, in update_D
    loss_D1_A = self.backward_D(self.disA, self.real_I_encoded, self.fake_I_encoded)
  File "/home/dengzeyu/run_on_server/Unsupervised-Domain-Specific-Deblurring-master/src/model.py", line 222, in backward_D
    ad_fake_loss = nn.functional.binary_cross_entropy(out_fake, all0)
  File "/home/dengzeyu/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 2113, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: device-side assert triggered
Do you know the reason？
Best

**Comment by suiyizhao** [comment]
I also encountered this problem. Have you solved it？

**Comment by huyi1998** [comment]
me too，how can I solve it?
